# Generated by Django 5.1.1 on 2025-01-23 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("room", models.CharField(max_length=100)),
                ("participants", models.IntegerField()),
                (
                    "participant1",
                    models.EmailField(default="default@example.com", max_length=254),
                ),
                (
                    "participant2",
                    models.EmailField(default="default@example.com", max_length=254),
                ),
                (
                    "participant3",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "participant4",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("terms", models.BooleanField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
