# Generated by Django 5.1.1 on 2025-01-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="terms",
            field=models.BooleanField(default=False),
        ),
    ]
